### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import random
import numpy as np

vector = [random.uniform(0, 1) for i in range (10)]
vector = np.array(vector)
print('Vector:', vector)

vector2 =  np.random.rand(10)
print('Vector2:', vector2)

matrix = np.array([[11, 14, 17],
              [20, 23, 26],
              [29, 32, 35]])
print(matrix)

vector.shape, vector2.shape, matrix.shape

Vector: [0.61677894 0.3048244  0.72233833 0.81509553 0.68138144 0.67532888
 0.51173226 0.26668238 0.16241578 0.8025552 ]
Vector2: [0.3780781  0.1760263  0.14987236 0.23958092 0.72779659 0.81915352
 0.54019657 0.82069494 0.49211333 0.79622731]
[[11 14 17]
 [20 23 26]
 [29 32 35]]


((10,), (10,), (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [2]:
vector = vector + 10
vector = np.round(vector, 2)
print(vector)

[10.62 10.3  10.72 10.82 10.68 10.68 10.51 10.27 10.16 10.8 ]


In [3]:
matrix_2 = matrix*2
print(matrix_2)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [4]:
vector_new = np.multiply(vector, vector)
print(vector_new)

[112.7844 106.09   114.9184 117.0724 114.0624 114.0624 110.4601 105.4729
 103.2256 116.64  ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [5]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [6]:
result_matrix = np.dot(B, A)
display(result_matrix)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [7]:
display(np.dot(result_matrix, C))

array([[0.5202],
       [0.2846]])

In [8]:
display(np.dot(result_matrix, D))

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [9]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [10]:
vector_trans = vector.T
print(vector_trans)
vector_trans.shape

[10.62 10.3  10.72 10.82 10.68 10.68 10.51 10.27 10.16 10.8 ]


(10,)

In [11]:
column_vector = np.expand_dims(vector, axis=1)
display(column_vector)
vector.shape, column_vector.shape

array([[10.62],
       [10.3 ],
       [10.72],
       [10.82],
       [10.68],
       [10.68],
       [10.51],
       [10.27],
       [10.16],
       [10.8 ]])

((10,), (10, 1))

In [12]:
display(column_vector.T)
display(column_vector.T.shape)

array([[10.62, 10.3 , 10.72, 10.82, 10.68, 10.68, 10.51, 10.27, 10.16,
        10.8 ]])

(1, 10)